-- 1. Création du rôle pour les outils
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ROLE_HUDSON;

-- 2. Création de l'infrastructure (le brief impose la taille XS et la base NYC_TAXI)
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS HUDSON_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;

-- 3. Attribution des droits au rôle (Principe de moindre privilège)
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE HUDSON_WH TO ROLE ROLE_HUDSON;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE ROLE_HUDSON;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI.RAW TO ROLE ROLE_HUDSON;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI.STAGING TO ROLE ROLE_HUDSON;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE ROLE_HUDSON;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI.MARTS TO ROLE ROLE_HUDSON;

-- 4. Création et configuration de l'utilisateur de service
CREATE USER IF NOT EXISTS SRV_HUDSON;
ALTER USER SRV_HUDSON SET 
  DEFAULT_ROLE = ROLE_HUDSON 
  DEFAULT_WAREHOUSE = HUDSON_WH
  DEFAULT_NAMESPACE = NYC_TAXI.RAW;

GRANT ROLE ROLE_HUDSON TO USER SRV_HUDSON;